import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { parseHTML } from 'linkedom';
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';

mkdirSync('test-results',{recursive:true});
const source = parseHTML(readFileSync('wikipedia-source.html','utf8')).document.querySelector('#mw-content-text .mw-parser-output');
const built = parseHTML(readFileSync('public/index.html','utf8')).document;
const article = built.querySelector('#article-content');
const textList = (doc, selector) => [...doc.querySelectorAll(selector)].map(e=>e.textContent.replace(/\s+/g,' ').trim());
assert.deepEqual(textList(article,'p:not(.reference-empty)'),textList(source,'p'),'All original article paragraphs must be preserved verbatim.');
assert.deepEqual(textList(article,'h2,h3,h4'),textList(source,'h2,h3,h4'),'All original section headings must be preserved.');
assert.deepEqual(textList(article,'.reference-text'),textList(source,'.reference-text'),'All notes and references must be preserved verbatim.');
assert.deepEqual(textList(article,'table.wikitable'),textList(source,'table.wikitable'),'All statistical tables must be preserved verbatim.');
assert.deepEqual(textList(article,'.infobox'),textList(source,'.infobox'),'The original infobox text must be preserved verbatim.');
assert.deepEqual(textList(article,'figcaption'),textList(source,'figcaption'),'All original media captions must be preserved verbatim.');
assert.deepEqual([...article.querySelectorAll('img')].map(e=>e.getAttribute('data-original-src')),[...source.querySelectorAll('img')].map(e=>new URL(e.getAttribute('src'),'https://en.wikipedia.org').href),'All original article images must be preserved in order.');
assert.equal(article.querySelectorAll('img:not([alt])').length,0,'Every image must have an alt attribute.');
const ids=[...built.querySelectorAll('[id]')].map(e=>e.id);
const duplicates=[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))];
assert.deepEqual(duplicates,[],'IDs must be unique.');
const invalidAnchors=[...built.querySelectorAll('a[href^="#"]')].filter(a=>{try{return !built.getElementById(decodeURIComponent(a.getAttribute('href').slice(1)));}catch{return true;}}).map(a=>a.getAttribute('href'));
assert.deepEqual(invalidAnchors,[],'Every local anchor must resolve.');
const checks={paragraphs:source.querySelectorAll('p').length,headings:source.querySelectorAll('h2,h3,h4').length,images:source.querySelectorAll('img').length,references:article.querySelectorAll('[data-reference]').length,contentParity:true};
console.log('Content preservation checks passed:',JSON.stringify(checks));
const browser=await chromium.launch({headless:true,channel:'chrome'});
const context=await browser.newContext({viewport:{width:1512,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
await page.locator('img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
await page.waitForFunction(()=>[...document.images].every(img=>img.complete));
assert.equal(await page.locator('img').evaluateAll(images=>images.filter(img=>img.naturalWidth===0).length),0,'All images must load.');
await page.screenshot({path:'test-results/desktop.png'});
console.log('Desktop loaded and all media verified.');

const runAxe=async(name)=>{
  const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();
  writeFileSync(`test-results/axe-${name}.json`,JSON.stringify(result.violations,null,2));
  console.log(`${name} accessibility:`,JSON.stringify(result.violations.map(v=>({id:v.id,impact:v.impact,count:v.nodes.length,examples:v.nodes.slice(0,3).map(n=>({target:n.target,summary:n.failureSummary}))}))));
  return result.violations;
};
checks.desktopAxe=await runAxe('desktop');
await page.keyboard.press('Tab');
assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Skip to article');
await page.keyboard.press('Enter');
assert.equal(await page.evaluate(()=>document.activeElement.id),'main-content');
const targetSizes=await page.locator('.toc-link:visible,.toc-toggle:visible,.account-actions .button:visible,.nav-group a:visible,.choice-content:visible').evaluateAll(els=>els.map(el=>({text:el.textContent.trim(),width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height})).filter(e=>e.height<44||e.width<44));
assert.deepEqual(targetSizes,[],'Improved navigation targets must be at least 44 × 44 CSS pixels.');
await page.getByRole('button',{name:'Expand Professional career subsections',exact:true}).click();
await page.locator('.contents-sidebar a[href="#2013:_First_PGA_Tour_win"]').click();
await page.waitForFunction(()=>location.hash.includes('2013'));
await page.locator('.contents-sidebar a[href="#References"]').click();
await page.waitForFunction(()=>document.activeElement?.id==='References');
await page.getByRole('searchbox',{name:'Search references',exact:true}).fill('zzzz-nothing-matches');
assert.equal(await page.locator('#reference-empty').isVisible(),true);
await page.getByRole('searchbox',{name:'Search references',exact:true}).fill('Masters');
assert.ok(await page.locator('[data-reference]:visible').count()>0);
assert.ok(await page.locator('[data-reference]:visible').count()<checks.references);
await page.getByRole('searchbox',{name:'Search references',exact:true}).fill('');
await page.screenshot({path:'test-results/references.png'});
assert.equal(await page.locator('.reference-citation .citation-primary').evaluateAll(links=>links.some(a=>a.getBoundingClientRect().height<44)),false,'Reference source links must have 44px targets.');
await page.locator('[data-reference="1"] .reference-return a').first().click();
assert.ok(await page.evaluate(()=>location.hash.startsWith('#cite_ref')));

await page.locator('.appearance-sidebar input[value="large"]').check();
assert.equal(await page.locator('html').getAttribute('data-size'),'large');
await page.reload({waitUntil:'networkidle'});
assert.equal(await page.locator('html').getAttribute('data-size'),'large','Preferences must persist.');
await page.locator('.appearance-sidebar [data-reset-appearance]').click();
await page.locator('.appearance-sidebar input[value="dark"]').check();
await page.locator('.back-to-top').click();
await page.screenshot({path:'test-results/dark.png'});
checks.darkAxe=await runAxe('dark');
await page.locator('.appearance-sidebar input[value="light"]').check();
await page.locator('.appearance-sidebar [data-open="accessibility-dialog"]').click();
await page.keyboard.press('Shift+Tab');
assert.equal(await page.locator('#accessibility-dialog').evaluate(el=>el.contains(document.activeElement)),true,'Keyboard focus must remain inside the open modal.');
await page.getByRole('switch',{name:'Higher contrast',exact:false}).check();
await page.getByRole('switch',{name:'Extra text spacing',exact:false}).check();
await page.getByRole('switch',{name:'Underline article links',exact:false}).check();
await page.screenshot({path:'test-results/accessibility.png'});
checks.dialogAxe=await runAxe('dialog');
await page.keyboard.press('Escape');
assert.equal(await page.locator('#accessibility-dialog').isVisible(),false);
assert.equal(await page.locator('.appearance-sidebar [data-open="accessibility-dialog"]').evaluate(el=>el===document.activeElement),true,'Dialog must restore focus.');
await page.locator('.appearance-sidebar [data-open="accessibility-dialog"]').click();
await page.getByRole('button',{name:'Reset all',exact:true}).click();
await page.getByRole('switch',{name:'Focus on the article',exact:false}).check();
await page.getByRole('button',{name:'Close accessibility menu',exact:true}).click();
assert.equal(await page.locator('.contents-sidebar').isVisible(),false);
assert.equal(await page.locator('.floating-accessibility').isVisible(),true);
await page.locator('.floating-accessibility').click();
await page.getByRole('switch',{name:'Reading guide',exact:false}).check();
await page.getByRole('button',{name:'Close accessibility menu',exact:true}).click();
assert.equal(await page.locator('.reading-guide-overlay').isVisible(),true);
const guideBefore=await page.locator('.reading-guide-overlay').boundingBox();
await page.keyboard.press('Alt+ArrowDown');
const guideAfter=await page.locator('.reading-guide-overlay').boundingBox();
assert.ok(guideAfter.y>guideBefore.y,'Reading guide must move using the keyboard.');
await page.locator('.floating-accessibility').click();
await page.getByRole('button',{name:'Reset all',exact:true}).click();
await page.getByRole('button',{name:'Close accessibility menu',exact:true}).click();
await page.getByRole('button',{name:'26 languages',exact:false}).click();
assert.equal(await page.locator('#languages-dialog .languages-list a').count(),26);
await page.keyboard.press('Escape');

for(const width of [1280,1024,768,390,320]){
  await page.setViewportSize({width,height:900});
  await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
  const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
  console.log('Viewport overflow check',overflow);
  assert.ok(overflow.scroll<=width+1,`No page-level horizontal overflow at ${width}px.`);
  await page.screenshot({path:`test-results/viewport-${width}.png`});
  if(width===390){
    await page.getByRole('button',{name:'Contents',exact:true}).click();
    await page.locator('#contents-dialog a[href="#Early_life"]').click();
    assert.equal(await page.locator('#contents-dialog').isVisible(),false);
    assert.equal(await page.evaluate(()=>document.activeElement?.id),'Early_life');
    await page.locator('.floating-accessibility').click();
    assert.equal(await page.locator('#accessibility-dialog').isVisible(),true);
    checks.mobileDialogAxe=await runAxe('mobile-dialog');
    await page.keyboard.press('Escape');
    checks.mobileAxe=await runAxe('mobile');
  }
}
assert.deepEqual(errors,[],'No browser JavaScript errors.');
for(const [name,result] of Object.entries(checks)) if(name.endsWith('Axe')) assert.equal(result.length,0,`${name} must have no automated accessibility violations.`);
writeFileSync('test-results/summary.json',JSON.stringify(checks,null,2));
await browser.close();
console.log('Browser behavior checks passed. See test-results for accessibility findings and screenshots.');
